-- Fix Expense table
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'Other';
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT 'Untitled';
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "receiptUrl" TEXT;

-- Fix LedgerEntity table
ALTER TABLE "LedgerEntity" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT 'Unknown';
ALTER TABLE "LedgerEntity" ADD COLUMN IF NOT EXISTS "openingBalance" DECIMAL(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE "LedgerEntity" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';

-- Fix LedgerTransaction table
ALTER TABLE "LedgerTransaction" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE "LedgerTransaction" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "LedgerTransaction" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "LedgerTransaction" ADD COLUMN IF NOT EXISTS "transactionDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "LedgerTransaction" ADD COLUMN IF NOT EXISTS "referenceNo" TEXT;

-- Fix User table
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "clerkId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL DEFAULT '';
