ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'Other';
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "note" TEXT;

ALTER TABLE "LedgerEntity" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "LedgerEntity" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "LedgerEntity" ADD COLUMN IF NOT EXISTS "balance" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "monthlyIncome" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "monthlyBudget" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "savingsGoal" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "onboardingComplete" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "clerkId" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "User_clerkId_key" ON "User"("clerkId");
